### ISSUE TITLE
Do you have any plans to support vue3?

### ISSUE THREAD

**Issue by nsano-rururu** [karoletrych/vue-cron-editor#84]

**Comment by karoletrych** [comment]
From what i understand Vue 2 components should work in Vue 3 projects. Haven't tested it though. I think i'll try to rewrite the sample app to Vue 3 to test it this week.

**Comment by karoletrych** [comment]
Ok, the component doesn't work on Vue3 at its current version. From what I've seen there is a difference in how TypeScript components are defined in Vue3. Propably some more differences (different versions of dependencies required(?)), so I guess I'll have to create separate npm package for Vue3 version. I'll keep working on this in my free time.

**Comment by nsano-rururu** [comment]
Looking at the issue of vuefy used by vue-cron-editor, it seems that vue3 is not supported. It looks like you're introducing a move to Oruga.
https://github.com/buefy/buefy/issues/2505

**Comment by EtoileFilante** [comment]
Hi there!

Is making it v3 compatible still something that is currently being worked on?

**Comment by karoletrych** [comment]
Hi, @EtoileFilante, sorry for late response:
I've experimented a bit with vue3 and oruga and it seems to be working. Unfortunately I don't have time/motivation to maintain this project anymore 😢 .
I've pushed the WIP to:
[feature/vue3-support](/karoletrych/vue-cron-editor/tree/feature/vue3-support)
finishing it would require:
1. testing it thorougly - the app in vue-cron-editor-oruga "seems" to be working now
2. possibly finding a way to share the common code ("core" directory) between the vue2 and vue3 components
3. adding demo app for vue3

I think I'll archive this project, since I don't plan on commiting to it anytime soon - I invite you to fork it.
